import Head from "next/head";
import Feed from "../components/Feed";
import Sidebar from "../components/Sidebar";
import Widgets from "../components/Widget";
import CommentModal from "../components/CommentModal";


export default function Home({newsResults, randomUsersResults}) {
  return (
    <>
      <Head>
        <title>Twitter Clone K19</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen  mx-auto ">
        {/* SideBar */}
        <Sidebar />
        {/* Feed */}
        <Feed />

        {/* Widgets */}
        <Widgets newsResults={newsResults.articles} randomUsersResults={randomUsersResults.results} />
        
        {/* Modals */}
        <CommentModal />
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const newsResults = await fetch(
    "https://saurav.tech/NewsAPI/top-headlines/category/business/us.json"
  ).then((res) => res.json());

  // who to follow section (used randomusergenerator with specified parameters only)

  const randomUsersResults = await fetch("https://randomuser.me/api/?results=30&inc=name,login,picture").then((res) => res.json());
  return {
   
    props: {
      newsResults,
      randomUsersResults
    },
  };
}
